config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :links

  get '/:hash_code', to: 'links#redirector'
  get '/:hash_code', to: 'links#preview'

end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
before_action 
	def index
		
	end

	def new
		@link = Link.new
	end

	def create
		@link = Link.new(safe_params)

		@link.hash_code = random_hash

		if @link.save
			redirect_to @link
		end
	end

	def show
		@link = Link.find(params[:id])
		@full_path = "#{request.protocol}#{request.host_with_port}/#{@link.hash_code}"

		
	end

	def redirectors
		@link = Link.find_by hash_code: params[:hash_code]
		if @link
			redirect_to @link.link
		else
			redirect_to root_path
		end
	end

	def preview
		@link = link.find_by hash_code: params[:hash_code]
		unless @link
			redirect_to root_path
		end
	end

	private 

	def safe_params
		params.require(:link).permit(:link)
		
	end

	def random_hash
		SecureRandom.urlsafe_base64(8)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome to Ritly</h1>
<p><%= link_to "Click here to create a new short link", new_link_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<h1>Welcome to Ritly!</h1>

<a href="http://localhost:3000/links/new"><h3>Create a new Ritly URL</h3></a>

app/views/links/new.html.erb
<h1>Create your new URL</h1>

<%= form_for @link do |f| %>
	<fieldset>
		<div class='fields'>
			<%= f.label :link, 'URL'%>
			<%= f.text_field :link %>
		</div>	
	</fieldset>
	<%= f.submit "Create my URL" %>
<% end %>

app/views/links/preview.html.erb
<h1>Code: <%= @link.hash_code %></h1>
<p>This code will take you to <%= @link.link %></p>
<%= link_to "Click Here", @link.link %> to continue 

app/views/links/show.html.erb
<h2><%= @link.hash_code %> is your code for <%= @link.link %></h2>

<h4>You can direct users to this Ritly URL: http://localhost:3000/<%= @link.hash_code %> </h4>

<h4>This Ritly URl will redirect them to <%= @link.link %></h4>